In [6]:
import torch

In [8]:
from transformers import MarianMTModel, MarianTokenizer

In [85]:
from torchvision import transforms

In [10]:
en_ROMANCE_model_name = 'Helsinki-NLP/opus-mt-en-ROMANCE'
en_ROMANCE_tokenizer = MarianTokenizer.from_pretrained(en_ROMANCE_model_name)
print(en_ROMANCE_tokenizer.supported_language_codes)

['>>fr<<', '>>es<<', '>>it<<', '>>pt<<', '>>pt_br<<', '>>ro<<', '>>ca<<', '>>gl<<', '>>pt_BR<<', '>>la<<', '>>wa<<', '>>fur<<', '>>oc<<', '>>fr_CA<<', '>>sc<<', '>>es_ES<<', '>>es_MX<<', '>>es_AR<<', '>>es_PR<<', '>>es_UY<<', '>>es_CL<<', '>>es_CO<<', '>>es_CR<<', '>>es_GT<<', '>>es_HN<<', '>>es_NI<<', '>>es_PA<<', '>>es_PE<<', '>>es_VE<<', '>>es_DO<<', '>>es_EC<<', '>>es_SV<<', '>>an<<', '>>pt_PT<<', '>>frp<<', '>>lad<<', '>>vec<<', '>>fr_FR<<', '>>co<<', '>>it_IT<<', '>>lld<<', '>>lij<<', '>>lmo<<', '>>nap<<', '>>rm<<', '>>scn<<', '>>mwl<<']


In [12]:
en_ROMANCE = MarianMTModel.from_pretrained(en_ROMANCE_model_name)

In [14]:
ROMANCE_en_model_name = 'Helsinki-NLP/opus-mt-ROMANCE-en'
ROMANCE_en_tokenizer = MarianTokenizer.from_pretrained(ROMANCE_en_model_name)


In [16]:
ROMANCE_en = MarianMTModel.from_pretrained(ROMANCE_en_model_name)

In [18]:
batch = ROMANCE_en_tokenizer.prepare_translation_batch(['>>en<< Este es un frase que queremos traducir a ingles'])
batch

{'input_ids': tensor([[    1,  1114,   124,    33, 16213,    15, 13380,   568, 24747,     9,
            13, 21182,     0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [20]:
translated = ROMANCE_en.generate(**batch)
[ROMANCE_en_tokenizer.decode(t) for t in translated]

['<pad> This is a phrase we want to translate into English']

In [22]:
translated

tensor([[65000,   182,    26,     9, 12461,   103,   329,    11, 22578,   232,
          1337]])

In [24]:
spanish = en_ROMANCE_tokenizer.prepare_translation_batch(['>>es<< This is a phrase we want to translate into Spanish'])

In [26]:
eng_to_spanish = en_ROMANCE.generate(**spanish)
[en_ROMANCE_tokenizer.decode(t) for t in eng_to_spanish]

['<pad> Esta es una frase que queremos traducir al español']

In [27]:
eng_to_spanish

tensor([[65000,  1427,   129,    92, 16216,    17, 13390,   560, 22503,   111,
         12412]])

In [28]:
en_ROMANCE??

In [124]:
partial_decode = torch.LongTensor([65000, 1427])
partial_decode.unsqueeze(0)

tensor([[65000,  1427]])

In [32]:
from transformers import MarianMTModel, MarianTokenizer

en_ROMANCE_model_name = 'Helsinki-NLP/opus-mt-en-ROMANCE'
en_ROMANCE_tokenizer = MarianTokenizer.from_pretrained(en_ROMANCE_model_name)
en_ROMANCE = MarianMTModel.from_pretrained(en_ROMANCE_model_name)

In [125]:
input_ids = en_ROMANCE_tokenizer.encode('>>es<< This is a phrase we want to translate into Spanish', return_tensors="pt")

english_encoded=en_ROMANCE.model.encoder(input_ids = input_ids)
partial_decode = torch.LongTensor([65000, 1427])

next_word_logits = en_ROMANCE(input_ids = input_ids,
                   encoder_outputs = english_encoded,
                   decoder_input_ids = partial_decode.unsqueeze(0))
next_word_logits

(tensor([[[nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan]]], grad_fn=<AddBackward0>),
 tensor([[[-2.0293e-01,  2.0769e-02,  2.8147e-02,  ...,  1.0518e+00,
            1.0340e-01, -8.8115e-02],
          [-3.6971e-01,  1.9407e-01,  2.8978e-01,  ...,  1.9322e+00,
            3.5916e-01,  1.1154e-03],
          [-3.5610e-01,  2.6620e-01,  1.5143e-01,  ...,  2.1092e+00,
           -1.0457e-01,  5.2787e-01],
          ...,
          [-6.9544e-02,  1.5759e-01,  3.8321e-01,  ...,  1.4983e+00,
            3.7078e-01,  8.3071e-03],
          [-2.8330e-01,  1.0562e-01,  2.4944e-01,  ...,  1.8255e+00,
            1.2717e-01, -1.2668e-01],
          [-3.3574e-03,  1.5221e-01,  2.5999e-01,  ...,  9.5313e-01,
           -2.8015e-02, -1.5033e-01]]], grad_fn=<TransposeBackward0>))

In [157]:
input_ids = en_ROMANCE_tokenizer.encode('>>es<< This is a phrase we want to translate into Spanish', return_tensors="pt")
batch = en_ROMANCE_tokenizer.prepare_translation_batch(['>>es<< This is a phrase we want to translate into Spanish'])
english_encoded = en_ROMANCE.get_encoder()(**batch)

past = (english_encoded, None)

model_inputs = en_ROMANCE.prepare_inputs_for_generation(
    partial_decode, past=past, attention_mask=batch['attention_mask'], use_cache=en_ROMANCE.config.use_cache
)
with torch.no_grad():
    model_outputs = en_ROMANCE(**model_inputs)
    
next_token_logits = model_outputs[0][:, -1, :]
past = model_outputs[1]

next_token_to_add = next_token_logits[0].argmax()
partial_decode = torch.cat((partial_decode, next_token_to_add.unsqueeze(0).unsqueeze(0)), -1)


ValueError: not enough values to unpack (expected 2, got 1)

In [681]:
ROMANCE_en_model_name = 'Helsinki-NLP/opus-mt-ROMANCE-en'
ROMANCE_en_tokenizer = MarianTokenizer.from_pretrained(ROMANCE_en_model_name)
ROMANCE_en = MarianMTModel.from_pretrained(ROMANCE_en_model_name)

In [685]:


tokenizer = en_ROMANCE_tokenizer
model = en_ROMANCE
#tokenizer = ROMANCE_en_tokenizer
#model = ROMANCE_en


english = ">>es<<Hello"
batch = tokenizer.prepare_translation_batch([english])
english_encoded = model.get_encoder()(**batch)
decoder_start_token = model.config.decoder_start_token_id

starting_word = tokenizer.convert_tokens_to_ids(tokenizer.tokenize("Hola"))
#starting_word = tokenizer.encode("A la")

partial_decode = torch.LongTensor([decoder_start_token]).unsqueeze(0)
past = (english_encoded, None)

prefix = torch.LongTensor(starting_word)
#prefix = torch.LongTensor(tokenizer.convert_tokens_to_ids("A la".replace(' ', '▁').split('▁')))
#prefix = torch.LongTensor(tokenizer.encode("A la"))
#prefix = torch.LongTensor(tokenizer.encode("A▁la▁"))

for x in range (0, 5):
    print(partial_decode)
    model_inputs = model.prepare_inputs_for_generation(
    partial_decode, past=past, attention_mask=batch['attention_mask'], use_cache=model.config.use_cache
    )
    with torch.no_grad():
        model_outputs = model(**model_inputs)

    next_token_logits = model_outputs[0][:, -1, :]
    past = model_outputs[1]
    
    if x < len(prefix):
        next_token_to_add = prefix[x]
        print(x, ": ", next_token_to_add)
    else:
        next_token_to_add = next_token_logits[0].argmax()
    
    partial_decode = torch.cat((partial_decode, next_token_to_add.unsqueeze(0).unsqueeze(0)), -1)
        

final = tokenizer.decode(partial_decode[0]).split("<pad>")[1]
print(final)

batch2 = ROMANCE_en_tokenizer.prepare_translation_batch([">>en<< " + final])
spanish_to_english = ROMANCE_en.generate(**batch2)
new_english = tokenizer.decode(spanish_to_english[0]).split("<pad>")[1]

new_english

tensor([[65000]])
0 :  tensor(9999)
tensor([[65000,  9999]])
1 :  tensor(55)
tensor([[65000,  9999,    55]])
tensor([[65000,  9999,    55,     3]])
tensor([[65000,  9999,    55,     3,     0]])
 Hola. Hola


' (▁felt.'

In [686]:
batch2

{'input_ids': tensor([[    1, 10467,     3, 10467,     0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1]])}

In [694]:
batch = ROMANCE_en_tokenizer.prepare_translation_batch([">>en<< Hola"])
spanish_to_english = ROMANCE_en.generate(**batch)
machine_translation = ROMANCE_en_tokenizer.decode(spanish_to_english[0]).split("<pad>")[1]

In [695]:
machine_translation

' - Hello.'

In [495]:
"A la".replace(' ', '▁').split('▁')

['A', 'la']

In [664]:
tokenizer.encode("A la")

[67, 11, 0]

In [665]:
tokenizer.convert_tokens_to_ids(tokenizer.tokenize("A la"))

[67, 11]

In [537]:
line = "A la tienda".split(' ')
first = [line[0]]
s =  ['▁'+e for e in line if line.index(e)>0]

for item in s:
    first.append(item)
    
first

['A', '▁la', '▁tienda']

In [638]:
en = tokenizer.encode("Las manzanas")
thelist = []
for token in en:
    h = tokenizer.convert_ids_to_tokens(token)
    thelist.append(h)
thelist

['▁Las', '▁man', 'zan', 'as', '</s>']

In [557]:
tokenizer.convert_tokens_to_ids(thelist)

[939, 476, 9364, 410, 0]

In [558]:
tokenizer.encode("Las manzanas")

[939, 476, 9364, 410, 0]

In [559]:
tokenizer.decode(torch.Tensor([21147]))

'Las'

In [675]:
tokenizer.convert_ids_to_tokens(0)

'</s>'

In [430]:
tokenizer.encode("<pad>A la", return_tensors="pt")[0]

tensor([65000,    67,    11,     0])

In [647]:
tokenizer.encode("A la")

[67, 11, 0]

In [648]:
tokenizer.convert_tokens_to_ids(["A", "la"])

[1]

In [428]:
tokenizer.convert_tokens_to_ids(" tienda".replace(' ', '▁'))

18103

In [667]:
tokenizer.convert_ids_to_tokens(3)

'.'

In [655]:
tokenizer.tokenize("Manzanas")

['▁Man', 'zan', 'as']

In [276]:
model.prepare_inputs_for_generation??

In [277]:
model.model??

In [258]:
final

'<pad> Corr a la tienda de la tienda a'

In [259]:
partial_decode

tensor([[65000, 10509,     9,    11, 18103,     5,    11, 18103,     9]])

In [261]:
final

'<pad> Corrí a la tienda.'

In [262]:
partial_decode

tensor([[65000, 10509,   620,     9,    11, 18103,     3,     0]])

In [256]:
batch

{'input_ids': tensor([[  16,   22, 7159,   12,    4, 5971,    3,    0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1]])}

In [257]:
english_encoded

(tensor([[[-1.8868e-01,  1.5954e-02,  5.3438e-02,  ...,  1.0132e+00,
            1.2336e-01, -2.1607e-02],
          [-6.8476e-01,  2.5475e-02, -2.3553e-01,  ...,  1.6161e+00,
           -5.6394e-01,  2.3299e-02],
          [-6.0008e-01,  1.3130e-01,  5.9747e-02,  ...,  1.7662e+00,
           -2.7124e-01,  1.7678e-01],
          ...,
          [-4.6728e-01, -1.4575e-01,  1.3083e-01,  ...,  1.6113e+00,
           -1.8874e-01,  1.1142e-01],
          [-1.4793e-02,  8.9173e-03, -1.9321e-01,  ...,  1.4010e+00,
           -3.5746e-01,  4.0463e-01],
          [-1.9166e-01,  1.9024e-04,  7.7792e-03,  ...,  8.7008e-01,
            6.2007e-02, -1.4011e-01]]], grad_fn=<TransposeBackward0>),
 [],
 [])

In [248]:
model.prepare_inputs_for_generation??

In [255]:
batch['attention_mask']

tensor([[1, 1, 1, 1, 1, 1, 1, 1]])

In [247]:
past

((tensor([[[-1.8868e-01,  1.5954e-02,  5.3438e-02,  ...,  1.0132e+00,
             1.2336e-01, -2.1607e-02],
           [-6.8476e-01,  2.5475e-02, -2.3553e-01,  ...,  1.6161e+00,
            -5.6394e-01,  2.3299e-02],
           [-6.0008e-01,  1.3130e-01,  5.9747e-02,  ...,  1.7662e+00,
            -2.7124e-01,  1.7678e-01],
           ...,
           [-4.6728e-01, -1.4575e-01,  1.3083e-01,  ...,  1.6113e+00,
            -1.8874e-01,  1.1142e-01],
           [-1.4793e-02,  8.9173e-03, -1.9321e-01,  ...,  1.4010e+00,
            -3.5746e-01,  4.0463e-01],
           [-1.9166e-01,  1.9024e-04,  7.7792e-03,  ...,  8.7008e-01,
             6.2007e-02, -1.4011e-01]]], requires_grad=True),
  tensor([[False, False, False, False, False, False, False, False]])),
 [{'self': {'prev_key': tensor([[[[ 1.6233,  0.3699,  1.2587,  ...,  0.8627,  0.0221, -0.6690],
              [-0.3883,  0.2948,  0.9705,  ...,  1.7831,  1.7119, -1.4530],
              [ 2.5376,  1.4050, -0.0922,  ...,  0.9905,  1.8753

In [245]:
english_encoded

(tensor([[[-1.8868e-01,  1.5954e-02,  5.3438e-02,  ...,  1.0132e+00,
            1.2336e-01, -2.1607e-02],
          [-6.8476e-01,  2.5475e-02, -2.3553e-01,  ...,  1.6161e+00,
           -5.6394e-01,  2.3299e-02],
          [-6.0008e-01,  1.3130e-01,  5.9747e-02,  ...,  1.7662e+00,
           -2.7124e-01,  1.7678e-01],
          ...,
          [-4.6728e-01, -1.4575e-01,  1.3083e-01,  ...,  1.6113e+00,
           -1.8874e-01,  1.1142e-01],
          [-1.4793e-02,  8.9173e-03, -1.9321e-01,  ...,  1.4010e+00,
           -3.5746e-01,  4.0463e-01],
          [-1.9166e-01,  1.9024e-04,  7.7792e-03,  ...,  8.7008e-01,
            6.2007e-02, -1.4011e-01]]], grad_fn=<TransposeBackward0>),
 [],
 [])

In [209]:
next_token_logits

tensor([[-1.2651, -7.9781, -3.3722,  ..., -7.9603, -7.9602,  0.0000]])

In [210]:
next_token_logits[0].argmax()

tensor(10509)

In [208]:
next_token_to_add

tensor(10509)

In [206]:
tokenizer.decode(torch.LongTensor([9261]))

'Hola'

In [204]:
tokenizer.convert_tokens_to_ids("Hola")

27754

In [280]:
eng_to_spanish = en_ROMANCE.generate(**batch, use_cache=False)
eng_to_spanish

ValueError: too many values to unpack (expected 2)

In [279]:
tokenizer.decode(eng_to_spanish[0])

'<pad> Corrí a la tienda.'

In [178]:
tokenizer.encode("Corr")

[10509, 0]

In [176]:
partial_decode = torch.cat((partial_decode, next_token_to_add.unsqueeze(0).unsqueeze(0)), -1)
partial_decode

tensor([[65000, 10509,     9]])

In [192]:
decoded = tokenizer.convert_ids_to_tokens(partial_decode[0])

In [193]:
tokenizer.decode(partial_decode[0])

'<pad> Corr'

In [164]:
model_inputs = model.prepare_inputs_for_generation(
    partial_decode, past=past, attention_mask=batch['attention_mask'], use_cache=model.config.use_cache
)
with torch.no_grad():
    model_outputs = model(**model_inputs)

next_token_logits = model_outputs[0][:, -1, :]
past = model_outputs[1]
next_token_to_add = next_token_logits[0].argmax()
partial_decode = torch.cat((partial_decode, next_token_to_add.unsqueeze(0).unsqueeze(0)), -1)
tokenizer.convert_ids_to_tokens(partial_decode[0])

['<pad>', '▁Corr', 'í']

In [145]:
with torch.autograd.detect_anomaly():
    next_word_logits = en_ROMANCE(input_ids = input_ids,
                   encoder_outputs = english_encoded,
                   decoder_input_ids = partial_decode.unsqueeze(0), requires_grad=True)
    next_word_logits[0].sum().backward()

RuntimeError: Function 'MmBackward' returned nan values in its 1th output.

In [141]:
next_word_logits[0]

tensor([[[nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan]]], grad_fn=<AddBackward0>)

In [151]:
en_ROMANCE.generate??

In [78]:
en_ROMANCE.model.encoder??

In [150]:
print(english_encoded[0][0].sum().backward(retain_graph=True))

RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.

In [111]:
transforms.Normalize(english_encoded[0][0], 1, 1)

Normalize(mean=tensor([[-2.0293e-01,  2.0769e-02,  2.8147e-02,  ...,  1.0518e+00,
          1.0340e-01, -8.8115e-02],
        [-3.6971e-01,  1.9407e-01,  2.8978e-01,  ...,  1.9322e+00,
          3.5916e-01,  1.1154e-03],
        [-3.5610e-01,  2.6620e-01,  1.5143e-01,  ...,  2.1092e+00,
         -1.0457e-01,  5.2787e-01],
        ...,
        [-6.9544e-02,  1.5759e-01,  3.8321e-01,  ...,  1.4983e+00,
          3.7078e-01,  8.3071e-03],
        [-2.8330e-01,  1.0562e-01,  2.4944e-01,  ...,  1.8255e+00,
          1.2717e-01, -1.2668e-01],
        [-3.3574e-03,  1.5221e-01,  2.5999e-01,  ...,  9.5313e-01,
         -2.8015e-02, -1.5033e-01]], grad_fn=<SelectBackward>), std=1)

In [48]:
en_ROMANCE.forward??

In [57]:
en_ROMANCE.model??

In [34]:
en_ROMANCE.generate??

In [52]:
:class:`Module`

SyntaxError: invalid syntax (<ipython-input-52-ec7d18a83f16>, line 1)

In [ ]:
next_word_logits[1][0][0].topk(5).indices

In [ ]:
en_ROMANCE_tokenizer.decode(next_word_logits[1][0][0].topk(5).indices)

In [ ]:
en_ROMANCE.model??

In [ ]:
english.input_ids

In [ ]:
en_ROMANCE_tokenizer.encode('>>es<< This is a phrase we want to translate into Spanish', return_tensors="pt")

In [ ]:
english.input_ids

In [ ]:
(english_encoded[0],)

In [ ]:
english_encoded[0]

In [ ]:
en_ROMANCE.model.encoder(input_ids = english.input_ids)