In [2]:
import torch
from transformers import T5Tokenizer, T5ForConditionalGeneration, T5Config, AutoTokenizer, AutoModelWithLMHead

In [3]:
model = T5ForConditionalGeneration.from_pretrained("t5-base")
tokenizer = T5Tokenizer.from_pretrained("t5-base")

In [168]:
tokenizer.decode(outputs1[0]).split(' ')

['Blumen', 'und', 'Sterne', 'sind', 'erstaunlich.']

In [ ]:
tokenizer.decode(prediction_scores[0][0].topk(4).indices).split(' ')[1]

In [172]:
output_ids[0]

tensor([    3, 28240,    14,    14,    14,    14,    14,    14,    14])

In [176]:
prediction_scores[0][2].topk(4).indices[0]

tensor(64)

In [49]:
    english = "When Liana Barrientos was 23 years old, she got married in Westchester County."
    german = "Liana fill fill fill fill fill fill fill fill fill fill fill fill fill fill fill fill fill fill fill fill fill"

    #encode english input with prefix
    input_ids = tokenizer.encode("translate English to German: " + english, return_tensors="pt")
    
    output_ids = tokenizer.encode(german, return_tensors='pt')

    for x in range (1, 22):
        outputs = model(input_ids=input_ids, lm_labels=output_ids)

        loss, prediction_scores = outputs[:2]

        second_choice = prediction_scores[0][x].topk(1).indices[0]
        output_ids[0][x] = second_choice

    final = tokenizer.decode(output_ids[0])


In [4]:
english = "I jump quickly and she runs slowly."
german = "Sie x x x x x x x x x x x"

input_ids = tokenizer.encode("translate English to German: " + english, return_tensors="pt")
    
output_ids = tokenizer.encode(german, return_tensors='pt')

for x in range (1, 12):
    outputs = model(input_ids=input_ids, lm_labels=output_ids)

    loss, prediction_scores = outputs[:2]

    first_choice = prediction_scores[0][x].topk(1).indices[0]
    output_ids[0][x] = first_choice
    print(tokenizer.decode(output_ids[0]))

final = tokenizer.decode(output_ids[0])


Sie x x x x x x x x x x x
Sie läuft x x x x x x x x x x
Sie läuft langsamx x x x x x x x x x
Sie läuft langsam und x x x x x x x x x
Sie läuft langsam und x x x x x x x x x
Sie läuft langsam und ich x x x x x x x x
Sie läuft langsam und ich springx x x x x x x x
Sie läuft langsam und ich springe x x x x x x x
Sie läuft langsam und ich springe schnellx x x x x x x
Sie läuft langsam und ich springe schnell. x x x x x x
Sie läuft langsam und ich springe schnell.x x x x x x


In [5]:
output_ids

tensor([[  292,     3, 15241, 20194,    64,     3,   362,  2141,    15,  3942,
             5,     1,   226,     3,   226,     3,   226,     3,   226,     3,
           226,     3,   226]])

In [105]:
final

'Sie läuft langsam und ich springe schnell.'

In [ ]:
tokenizer.decode(prediction_scores[0][22])

In [5]:
    english = "She jumps and I run"
    german = "Ich"

    #encode english input with prefix
    input_ids = tokenizer.encode("translate English to German: " + english, return_tensors="pt")
    output_ids = tokenizer.encode(german, return_tensors='pt')

    for x in range (1, 8):
        
        print(german)
        output_ids[0] = torch.cat((output_ids[0], torch.tensor([5])), 0)
        
        outputs = model(input_ids=input_ids, lm_labels=output_ids)
        loss, prediction_scores = outputs[:2]

        second_choice = prediction_scores[0][x].topk(1).indices[0]
        output_ids[0][x] = second_choice

    german = tokenizer.decode(output_ids[0])


Ich


RuntimeError: The expanded size of the tensor (1) must match the existing size (2) at non-singleton dimension 0.  Target sizes: [1].  Tensor sizes: [2]

In [127]:
output_ids[0]

tensor([1674,    3, 7832,   15,   64,  680, 2141,   15,   14])

In [136]:
 torch.cat((output_ids[0], torch.tensor([5])), 0)

tensor([1674,   14,   14,   14,   14,   14,   14,   14,   14,    5])

In [125]:
german = "Ich fill fill fill fill fill fill fill fill"
english = "She jumps and I run"

for x in range (1, 8):

    #encode english input with prefix
    input_ids = tokenizer.encode("translate English to German: " + english, return_tensors="pt")
    output_ids = tokenizer.encode(german, return_tensors='pt')

    print(german)
    
    outputs = model(input_ids=input_ids, lm_labels=output_ids)
    loss, prediction_scores = outputs[:2]

    second_choice = prediction_scores[0][x].topk(1).indices[0]
    output_ids[0][x] = second_choice

end = tokenizer.decode(output_ids[0])


Ich fill fill fill fill fill fill fill fill
Ich fill fill fill fill fill fill fill fill
Ich fill fill fill fill fill fill fill fill
Ich fill fill fill fill fill fill fill fill
Ich fill fill fill fill fill fill fill fill
Ich fill fill fill fill fill fill fill fill
Ich fill fill fill fill fill fill fill fill


In [126]:
end

'Ich laufe und sie springe fill'

In [27]:
prediction_scores[0][1].topk(1).indices[0]

tensor(3)

In [272]:
tokenizer.encode("fill", return_tensors="pt")[0]

tensor([14])

In [275]:
torch.cat((output_ids[0], tokenizer.encode("fill", return_tensors="pt")[0]), 0)

tensor([1674,   14])

In [258]:
final

'Ich laufe und sie springe fill'

In [ ]:
second_choice

In [198]:
tokenizer.decode(prediction_scores[0][2].topk(4).indices).split(' ')[0]

'und'

In [60]:
[tokenizer.decode(g, skip_special_tokens=True, clean_up_tokenization_spaces=False) for g in input_ids]

['translate English to German: translate English to German: When Liana Barrientos was 23 years old, she got married in Westchester County.']

In [61]:
[tokenizer.decode(g, skip_special_tokens=True, clean_up_tokenization_spaces=False) for g in output_ids]

['Als Liana Barrientos 23 Jahre alt war, heiratete sie in Westchester County.']

In [62]:
outputs1

tensor([[    0,  1985,   340,   304,    26,  1159,     7, 19450,     7,     3,
         17265,     9, 14810,   680,    16,  1244, 13263,  1334,     6,   368,
          1060,     5]])

In [63]:
[tokenizer.decode(g, skip_special_tokens=True, clean_up_tokenization_spaces=False) for g in outputs1]

['Nach dem Tod ihres Vaters heiratete sie in Westchester County, New York.']

In [64]:
prediction_scores

tensor([[[-18.5946,  -8.1854, -13.3654,  ..., -40.5977, -40.6532, -40.4892],
         [-31.9207, -13.5465, -13.5772,  ..., -45.3452, -45.3538, -45.4147],
         [-52.3096, -25.5499, -20.8803,  ..., -65.2021, -65.0031, -65.2328],
         ...,
         [-46.6869, -20.4712, -18.4204,  ..., -56.4153, -56.3651, -56.2740],
         [-33.2802, -13.0266, -12.1969,  ..., -46.4536, -46.5405, -46.4559],
         [-38.1263, -14.5747, -16.3950,  ..., -54.0799, -54.2224, -54.2078]]],
       grad_fn=<UnsafeViewBackward>)

In [65]:
prediction_scores[0]

tensor([[-18.5946,  -8.1854, -13.3654,  ..., -40.5977, -40.6532, -40.4892],
        [-31.9207, -13.5465, -13.5772,  ..., -45.3452, -45.3538, -45.4147],
        [-52.3096, -25.5499, -20.8803,  ..., -65.2021, -65.0031, -65.2328],
        ...,
        [-46.6869, -20.4712, -18.4204,  ..., -56.4153, -56.3651, -56.2740],
        [-33.2802, -13.0266, -12.1969,  ..., -46.4536, -46.5405, -46.4559],
        [-38.1263, -14.5747, -16.3950,  ..., -54.0799, -54.2224, -54.2078]],
       grad_fn=<SelectBackward>)

In [66]:
for word in prediction_scores[0]:
    print(word.topk(3).indices)

tensor([4746,  316, 1985])
tensor([301,  67, 680])
tensor([13662, 21247, 23306])
tensor([1386,  181, 1207])
tensor([3483, 5288, 1753])
tensor([235,  17,  32])
tensor([   7,    3, 1902])
tensor([1902,  256,  181])
tensor([3861, 3093,  615])
tensor([4445,  615, 2105])
tensor([ 615, 1177,  229])
tensor([  6,   3, 548])
tensor([   3,  548, 1177])
tensor([17265,   547, 17328])
tensor([  9, 342, 144])
tensor([14810,   324,    17])
tensor([680,   3, 388])
tensor([256,  16, 211])
tensor([1244,   74,  340])
tensor([13263, 20976,    18])
tensor([1334,    5,    6])
tensor([5, 3, 6])


In [52]:
prediction_scores[0][0].topk(3).indices

tensor([4746,  316, 1985])

In [67]:
all_predictions

[(('Als', 'lime'), ['Als', 'Die', 'Nach', 'In', 'Sie']),
 (('L', 'lime'), ['L', 'die', 'sie', '', 'sich']),
 (('iana', 'lime'), ['iana', 'yana', 'illian', 'anna', 'iano']),
 (('Bar', 'lime'), ['Bar', 'mit', 'bar', '', 'schon']),
 (('rien', 'lime'), ['rien', 'rian', 'rie', 'rios', 'r']),
 (('to', 'lime'), ['to', 't', 'o', '<unk>', 's']),
 (('s', 'lime'), ['s', '', '23', 'im', 'mit']),
 (('23', 'lime'), ['23', 'im', 'mit', '23,', '22']),
 (('Jahre', 'lime'), ['Jahre', 'Jahren', 'war', 'jährige', '.']),
 (('alt', 'lime'), ['alt', 'war', 'alte', '', 'old']),
 (('war', 'lime'), ['war', 'wurde', 'ist', 'geworden', ',']),
 ((',', 'lime'), [',', '', 'ver', 'wurde', 'und']),
 (('', 'lime'), ['', 'ver', 'wurde', 'ge', 'began']),
 (('heir', 'lime'), ['heir', 'hat', 'zog', 'e', 'er']),
 (('a', 'lime'), ['a', 'ate', 'at', 'aß', 'ates']),
 (('tete', 'lime'), ['tete', 'ten', 't', 'ter', 's']),
 (('sie', 'lime'), ['sie', '', 'man', 'die', 'ihr']),
 (('in', 'yellow'), ['im', 'in', 'das', 'sich', 'die']

In [83]:
tokenizer??